const Replacements = {
    "u": "you",
    "y'all": "you all",
    "ya": "you",
    "yr": "your",
    "youre": "you're",
    "r": "are",
    "ur": "your",
    "b": "be",
    "bae" : "baby",
    "cuz": "because",
    "c": "see",
    "n": "and",
    "nd": "and",
    "dis": "this",
    "dat": "that",
    "dem": "them",
    "rn": "right now",
    "thx": "thanks",
    "ty": "thank you",
    "thnx": "thanks",
    "pls": "please",
    "plz": "please",
    "prblm": "problem",
    "omg": "oh my god",
    "ttyl": "talk to you later",
    "brb": "be right back",
    "gtg": "got to go",
    "idk": "I don't know",
    "btw": "by the way",
    "imo": "in my opinion",
    "lmk": "let me know",
    "tbh": "to be honest",
    "w/e": "whatever",
    "w/o": "without",
    "cya": "see you",
    "gr8": "great",
    "b4": "before",
    "bc": "because",
    "smh": "shaking my head",
    "nvm": "never mind",
    "afaik": "as far as I know",
    "fwiw": "for what it's worth",
    "ftw": "for the win",
    "idc": "I don't care",
    "ilu": "I love you",
    "ily": "I love you",
    "jk": "just kidding",
    "np": "no problem",
    "rofl": "rolling on the floor laughing",
    "sry": "sorry",
    "wth": "what the heck",
    "bbl": "be back later",
    "bfn": "bye for now",
    "hbu": "how about you",
    "ic": "I see",
    "ily2": "I love you too",
    "k": "okay",
    "kk": "okay",
    "u2": "you too",
    "u2u": "you to you",
    "wbu": "what about you",
    "y": "why",
    "g2g": "got to go",
    "gn": "good night",
    "gm": "good morning",
    "yw": "you're welcome",
    "lol": "laugh out loud",
    "w8": "wait",
    "b/c": "because",
    "bday": "birthday",
    "bff": "best friends forever",
    "bf": "boyfriend",
    "gf": "girlfriend",
    "j/k": "just kidding",
    "l8r": "later",
    "msg": "message",
    "omw": "on my way",
    "ppl": "people",
    "srsly": "seriously",
    "tldr": "too long didn't read",
    "wtf": "what the fuck",
    "wyd": "what are you doing",
    "bcuz": "because",
    "b4n": "bye for now",
    "hapy":"happy",
    "bgd": "background",
    "bgr": "background",
    "bhl8": "be home late",
    "bih": "b**** in heat",
    "bij": "b**** in jail",
    "bl": "bad luck",
    "bm": "bite me",
    "bom": "blow off meeting",
    "br": "best regards",
    "c&g": "chuckle and grin",
    "cba": "can't be arsed",
    "cc": "carbon copy",
    "cfs": "care for some",
    "cid": "crying in disgrace",
    "cmiiw": "correct me if I’m wrong",
    "ctn": "can’t talk now",
    "cu": "see you",
    "cul": "see you later",
    "cwot": "complete waste of time",
    "cy": "see you",
    "cyal8r": "see you later",
    "cyt": "see you tomorrow",
    "dbeyr": "don't believe everything you read",
    "dh": "dear husband",
    "dm": "direct message",
    "doin": "doing",
    "dr": "dear",
    "dunno": "don’t know",
    "dyd": "do you drink",
    "dyk": "did you know",
    "e1": "everyone",
    "eg": "evil grin",
    "eod": "end of discussion",
    "ez": "easy",
    "sassy":"sexy",
    "f2f": "face to face",
    "f2p": "free to play",
    "f8": "fate",
    "faq": "frequently asked questions",
    "fav": "favorite",
    "fb": "Facebook",
    "ffs": "for fuck’s sake",
    "fomo": "fear of missing out",
    "fo": "fuck off",
    "fud": "fear, uncertainty, and doubt",
    "fw": "forward",
    "fwd": "forward",
    "fy": "fuck you",
    "fyi": "for your information",
    "g9": "genius",
    "gag": "get a grip",
    "gal": "get a life",
    "gbh": "great big hug",
    "gbml": "god bless my life",
    "gd": "good",
    "gl": "good luck",
    "gnite": "good night",
    "gr8t": "great",
    "gratz": "congratulations",
    "ha": "hello again",
    "hagn": "have a good night",
    "hand": "have a nice day",
    "haxor": "hacker",
    "hf": "have fun",
    "hmu": "hit me up",
    "hotd": "headline of the day",
    "hr": "hour",
    "ht": "hat tip",
    "hv": "have",
    "icq": "I seek you",
    "idgi": "I don’t get it",
    "idn": "I don’t know",
    "iff": "if and only if",
    "ikr": "I know right",
    "ilysm": "I love you so much",
    "ilu2": "I love you too",
    "ilyt": "I love you too",
    "im": "instant message",
    "imho": "in my honest opinion",
    "imnsho": "in my not so humble opinion",
    "inb4": "in before",
    "irl": "in real life",
    "iso": "in search of",
    "itt": "in this thread",
    "iydmma": "if you don’t mind me asking",
    "j/p": "just playing",
    "j/w": "just wondering",
    "jelly": "jealous",
    "jfgi": "just fucking google it",
    "jsyk": "just so you know",
    "kbye": "ok, bye",
    "kthx": "okay, thanks",
    "kthxbye": "okay, thanks, bye",
    "kys": "kill yourself",
    "l8": "late",
    "l8er": "later",
    "l8tr": "later",
    "lawl": "laughing out loud",
    "ldr": "long-distance relationship",
    "lmao": "laughing my ass off",
    "lmfao": "laughing my fucking ass off",
    "lolz": "laughing out loud",
    "lqtms": "laughing quietly to myself",
    "ltns": "long time no see",
    "lvu": "love you",
    "luv": "love",
    "m8": "mate",
    "mb": "my bad",
    "mwah": "kiss",
    "nbd": "no big deal",
    "nm": "not much",
    "nmh": "not much here",
    "nsfw": "not safe for work",
    "nth": "nothing",
    "ntg":"nothing",
    "oic": "oh, I see",
    "omfg": "oh my fucking god",
    "ot": "off topic",
    "pov": "point of view",
    "prolly": "probably",
    "qt": "cutie",
    "rl": "real life",
    "roflcopter": "rolling on the floor laughing",
    "rs": "real shit",
    "rpg": "role-playing game",
    "rt": "retweet",
    "snafu": "situation normal all fucked up",
    "soz": "sorry",
    "sup": "what’s up",
    "swag": "style",
    "tmi": "too much information",
    "ttys": "talk to you soon",
    "txt": "text",
    "w00t": "woot",
    "wtg": "way to go",
    "wut": "what",
    "wat": "what",
    "gud":"good",
    "n8":"night",
    "ni8":"night",
    "yolo": "you only live once",
    "afk": "away from keyboard",
    "tba": "to be announced",
    "atm": "at the moment",
    "aamof": "as a matter of fact",
    "afaic": "as far as I’m concerned",
    "afaict": "as far as I can tell",
    "afair": "as far as I remember",
    "aiui": "as I understand it",
    "aka": "also known as",
    "asap": "as soon as possible",
    "bbiab": "be back in a bit",
    "bbl8r": "be back later",
    "bbq": "barbecue",
    "bcnu": "be seeing you",
    "aren't": "are not", 
    "can't": "cannot", 
    "couldn't": "could not", 
    "didn't": "did not", 
    "doesn't": "does not", 
    "don't": "do not", 
    "hadn't": "had not", 
    "hasn't": "has not", 
    "haven't": "have not", 
    "he'd": "he would", 
    "he'll": "he will", 
    "he's": "he is", 
    "i'd": "I would", 
    "i'll": "I will", 
    "i'm": "I am", 
    "fyn":"fine",
    "i've": "I have",
    "hru":"how are you",
    "isn't": "is not", 
    "it's": "it is", 
    "it'll": "it will", 
    "i've": "I have", 
    "let's": "let us", 
    "mightn't": "might not", 
    "mustn't": "must not", 
    "shan't": "shall not", 
    "she'd": "she would", 
    "she'll": "she will", 
    "she's": "she is", 
    "shouldn't": "should not", 
    "that's": "that is", 
    "there's": "there is", 
    "they'd": "they would", 
    "they'll": "they will", 
    "they're": "they are", 
    "they've": "they have", 
    "we'd": "we would", 
    "we're": "we are", 
    "weren't": "were not", 
    "we've": "we have", 
    "what'll": "what will", 
    "what're": "what are", 
    "what's": "what is", 
    "what've": "what have", 
    "where's": "where is", 
    "who'd": "who would", 
    "who'll": "who will", 
    "who're": "who are", 
    "who's": "who is", 
    "who've": "who have", 
    "won't": "will not", 
    "wouldn't": "would not", 
    "you'd": "you would", 
    "you'll": "you will", 
    "you're": "you are", 
    "you've": "you have", 
    "'re": " are", 
    "wasn't": "was not", 
    "we'll": " will",
   "yass":"yes",
   "okey":"okay",
   'rn':"right now",
    '<3': "love",
     ':)': "smile",
     ':(': "sad",
     ':D': "grin",
     'fynn':'fine',
     'XD': "laugh",
     ':-O': "surprised",
     ':P': "tongue out",
     ':-*': "kiss",
     ';)': "wink",
     ':/': "confused",
     ':|': "neutral",
     '>:(': "angry",
     'T_T': "crying",
     ':3': "cat smile",
     'O:)': "angel",
     '>:O': "shocked",
     'B)': "cool",
     'D:': "horror",
     '8)': "nerdy",
     '<_<': "skeptical",
     '>_>': "suspicious",
     '^^': "happy",
     ':@': "frustrated",
     ':$': "embarrassed",
     '>:D<': "hug",
     ':-?': "thinking",
     ':S': "worried",
     ':|]': "robot",
     ':^)': "smirk",
     ':-#': "sealed lips",
     ':X': "no comment",
     'o.O': "perplexed",
     '-_-': "unamused",
     ':)': "smiley",
     '(y)': "thumbs up",
     '(n)': "thumbs down",
     ':0)': "clown",
     ':])': "happy face",
     ':[)': "sad face",
     ';^)': "wink smile",
     ':-)': "classic smile",
     ':-(': "classic frown",
     ':8)': "nerdy smile",
     'xD': "laughing hard",
     ':-P': "playful",
     ':-S': "worried",
     ':-|': "indifferent",
     ':*-*': "kiss kiss",
     '^_^': "joy",
     '-.-': "bored",
     'O.O': "astonished",
     ':<': "disappointed",
     '>:)': "evil grin",
     '8D': "big grin",
     ':B': "bucktooth smile",
     ':o)': "monkey smile",
     '=)': "equal smile",
     '=D': "equal grin",
     '>:P': "cheeky",
     ':@)': "pig smile",
     ':-&': "sick",
     ':#': "mute",
     '<(")': "penguin",
     ':>)': "clown face",
     '<^_^>': "hugging",
     '^_^;': "nervous smile",
     ':*': "blowing kiss",
     ':])': "robot smile",
     ':/)': "skeptical smile",
     ':^)': "raised eyebrow",
     ':o)': "monkey face",
     ':-b': "tasting",
     '=]': "happy",
     ':-]': "smile",
     ':-)': "happy",
     '>:[': "angry",
     ':-x': "kiss",
     ':-X': "sealed lips",
     'B-)': "cool",
     'o_O': "confused",
     '0:)': "innocent",
     '>:D': "laughing",
     '>:)': "evil smile",
     ':-d': "licking lips",
     ':-/': "skeptical",
     ':-t': "playful",
     ':]': "content",
     ':-!': "foot in mouth",
     ':-[': "embarrassed",
     ':-]': "happy",
     ':|': "neutral",
     ';P': "playful wink",
     ';-P': "playful wink",
     'o_o': "shocked",
     '-.-': "bored",
     ':]': "grin",
     ':}': "smile",
     ':{': "frown",
     ':]': "smirk",
     ':}': "content",
     ':{': "discontent",
     ';D': "winking smile",
     ';]': "winking",
     ';[': "annoyed",
     ':))': "laughing",
     ':))': "big laugh",
     ':-))': "double chin laugh",
     ':))': "happy",
     ';-)': "winking",
     ';D': "wink",
     ':-)': "smile",
     ':-))': "very happy",
     ':-[': "embarrassed",
     ':-]': "happy",
     ':|': "indifferent",
     ':)': "smile",
     ':(': "frown",
     ':D': "grin",
     ':P': "playful",
     ';-)': "winking",
     'B)': "cool",
     ':*)': "blushing",
     ';-)': "winking",
     ':o)': "monkey face",
     ':-[': "embarrassed",
     ':-]': "happy",
     ':-|': "indifferent",
     ':)': "smile",
     ':(': "frown",
     ':D': "grin",
     ':P': "playful",
     ';)': "wink",
     'B)': "cool",
     ':-[': "embarrassed",
     ':-]': "happy",
     ':-|': "indifferent",
     ':)': "smile",
     ':(': "frown",
     ':D': "grin",
     ':P': "playful",
     ';)': "wink",
     'B)': "cool",
     ':-[': "embarrassed",
     ':-]': "happy",
     ':-|': "indifferent",
     ':)': "smile",
     ':(': "frown",
     ':D': "grin",
     ':P': "playful",
     ';)': "wink",
     'B)': "cool",
     ':[': "sad face"
  } 
  


  const ExpandedReplacements={}
  Object.entries(Replacements).forEach(([key, value]) => {
    ExpandedReplacements[key] = value;
    ExpandedReplacements[key + ','] = value;
    ExpandedReplacements[key + '!'] = value;
    ExpandedReplacements[key + '?'] = value;
  });
  
  export default ExpandedReplacements;
  
  
  